//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivitySampling.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivitySampling.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Sampling halted.
        /// </summary>
        internal static string BL_EndMessage {
            get {
                return ResourceManager.GetString("BL_EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... changed.
        /// </summary>
        internal static string BL_ScreenChangedInfo {
            get {
                return ResourceManager.GetString("BL_ScreenChangedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... closing.
        /// </summary>
        internal static string BL_ScreenEndingInfo {
            get {
                return ResourceManager.GetString("BL_ScreenEndingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [press &apos;h&apos; for help].
        /// </summary>
        internal static string BL_ScreenMenuInfo {
            get {
                return ResourceManager.GetString("BL_ScreenMenuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... saved.
        /// </summary>
        internal static string BL_ScreenSavedInfo {
            get {
                return ResourceManager.GetString("BL_ScreenSavedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ....
        /// </summary>
        internal static string BL_ScreenStartingInfo {
            get {
                return ResourceManager.GetString("BL_ScreenStartingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Sampling started.
        /// </summary>
        internal static string BL_StartMessage {
            get {
                return ResourceManager.GetString("BL_StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;x&apos; = exit
        ///&apos;a&apos; = add action
        ///&apos;e&apos; = edit last activity.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [press &apos;return&apos; to use last activity].
        /// </summary>
        internal static string InputHint {
            get {
                return ResourceManager.GetString("InputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no activity.
        /// </summary>
        internal static string NoActionText {
            get {
                return ResourceManager.GetString("NoActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Sampling V1.
        /// </summary>
        internal static string Program_Main_Activity_Sampling_V1 {
            get {
                return ResourceManager.GetString("Program_Main_Activity_Sampling_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application halted..
        /// </summary>
        internal static string Program_Main_Application_halted_ {
            get {
                return ResourceManager.GetString("Program_Main_Application_halted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you doing now?.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
    }
}
